# Generated by Django 4.2.3 on 2023-07-06 04:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entry', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_exit', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entry', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_exit', models.DateTimeField(default=django.utils.timezone.now)),
                ('ubication', models.CharField(default='', max_length=200)),
                ('id_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
            ],
        ),
        migrations.CreateModel(
            name='Contract_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
                ('id_Contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.contract')),
            ],
        ),
    ]
