# Generated by Django 4.2.3 on 2023-07-11 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0002_vehicle_id_parking'),
        ('Client', '0004_remove_contract_cost_client_identification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='id_Vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Receipt_Vehicle', to='Vehicle.vehicle'),
        ),
    ]
