# Generated by Django 4.2.3 on 2023-07-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_alter_receipt_date_exit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='cost',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
