# Generated by Django 4.2.3 on 2023-07-12 02:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_alter_receipt_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date_entry',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_exit',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
