# Generated by Django 4.2.3 on 2023-07-13 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0002_vehicle_id_parking'),
        ('Client', '0008_alter_receipt_date_entry_alter_receipt_date_exit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='id_Vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Receipt_Vehicle', to='Vehicle.vehicle'),
        ),
    ]
