# Generated by Django 4.2.3 on 2023-07-13 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_alter_receipt_id_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='id_Vehicle',
        ),
    ]
