# Generated by Django 4.2.3 on 2023-07-14 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0012_alter_client_identification_alter_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_entry',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_exit',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('dia', 'Día'), ('semana', 'Semana'), ('mes', 'Mes'), ('año', 'Año')], default='', max_length=200),
        ),
    ]
