# Generated by Django 4.2.3 on 2023-07-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0013_alter_contract_date_entry_alter_contract_date_exit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
