# Generated by Django 4.2.3 on 2023-07-17 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0017_alter_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date_entry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_exit',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
