# Generated by Django 4.2.3 on 2023-07-17 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0007_alter_vehicle_type'),
        ('Client', '0019_alter_receipt_ubication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='id_Vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vehicle.vehicle'),
        ),
    ]
