# Generated by Django 4.2.3 on 2023-07-17 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0021_alter_receipt_id_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='id_Client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.client'),
        ),
    ]
