# Generated by Django 4.2.3 on 2023-07-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='', max_length=200)),
                ('plate', models.CharField(default='', max_length=200)),
                ('brand', models.CharField(default='', max_length=200)),
                ('model', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
