# Generated by Django 4.2.3 on 2023-07-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0002_parking_id_admin'),
        ('Vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='id_Parking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Parking.parking'),
        ),
    ]
