# Generated by Django 4.2.3 on 2023-07-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0003_alter_vehicle_brand_alter_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('auto', 'Automovil'), ('heavy', 'Vehículos Pesados'), ('moto', 'Motocicletas')], default='', max_length=200),
        ),
    ]
