# Generated by Django 4.2.3 on 2023-07-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0004_alter_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
