# Generated by Django 4.2.3 on 2023-07-06 02:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_admin_bill_delete_tarifa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='contraseña',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='t_Contrato',
            new_name='t_contract',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='zona',
            new_name='zone',
        ),
        migrations.AddField(
            model_name='bill',
            name='date_entry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bill',
            name='date_exit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
