# Generated by Django 4.2.3 on 2023-07-11 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_rename_t_contract_bill_value_motos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='zone',
            new_name='value_Zone',
        ),
    ]
