# Generated by Django 4.2.3 on 2023-07-11 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_rename_zone_bill_value_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='value_Motos',
            new_name='values_Motos',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='value_Zone',
            new_name='values_Zone',
        ),
    ]
